// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 578p2KiWp3ZSUFPY7FrhK3
// Component: iof-KKxyHO
import * as React from "react";
import Link from "next/link";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  useTrigger,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { useScreenVariants as useScreenVariantstU3UFp3Zwbn8D } from "../new_ones/PlasmicGlobalVariant__Screen"; // plasmic-import: _tU3UFp3Zwbn8d/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "../new_ones/plasmic_new_ones.module.css"; // plasmic-import: 578p2KiWp3ZSUFPY7FrhK3/projectcss
import sty from "./PlasmicHeading1GoogleUxChallenge.module.css"; // plasmic-import: iof-KKxyHO/css
import ArrowUpRightIcon from "../new_ones/icons/PlasmicIcon__ArrowUpRight"; // plasmic-import: xa6I7_9Y9zpgmB/icon

export const PlasmicHeading1GoogleUxChallenge__VariantProps = new Array();

export const PlasmicHeading1GoogleUxChallenge__ArgProps = new Array();

function PlasmicHeading1GoogleUxChallenge__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;
  const [isRootHover, triggerRootHoverProps] = useTrigger("useHover", {});
  const triggers = {
    hover_root: isRootHover
  };

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantstU3UFp3Zwbn8D()
  });

  return (
    <p.PlasmicLink
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.a,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
      component={Link}
      href={triggers.hover_root ? "/google-ux" : undefined}
      platform={"nextjs"}
      target={triggers.hover_root ? "_blank" : undefined}
      data-plasmic-trigger-props={[triggerRootHoverProps]}
    >
      <div
        data-plasmic-name={"heading2"}
        data-plasmic-override={overrides.heading2}
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.heading2
        )}
      >
        {"Google UX Course Challenge"}
      </div>

      <div
        data-plasmic-name={"iconWrap2"}
        data-plasmic-override={overrides.iconWrap2}
        className={classNames(projectcss.all, sty.iconWrap2)}
      >
        <ArrowUpRightIcon
          data-plasmic-name={"svg"}
          data-plasmic-override={overrides.svg}
          className={classNames(projectcss.all, sty.svg)}
          role={"img"}
        />
      </div>
    </p.PlasmicLink>
  );
}

const PlasmicDescendants = {
  root: ["root", "heading2", "iconWrap2", "svg"],
  heading2: ["heading2"],
  iconWrap2: ["iconWrap2", "svg"],
  svg: ["svg"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHeading1GoogleUxChallenge__ArgProps,
      internalVariantPropNames: PlasmicHeading1GoogleUxChallenge__VariantProps
    });

    return PlasmicHeading1GoogleUxChallenge__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHeading1GoogleUxChallenge";
  } else {
    func.displayName = `PlasmicHeading1GoogleUxChallenge.${nodeName}`;
  }
  return func;
}

export const PlasmicHeading1GoogleUxChallenge = Object.assign(
  // Top-level PlasmicHeading1GoogleUxChallenge renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    heading2: makeNodeComponent("heading2"),
    iconWrap2: makeNodeComponent("iconWrap2"),
    svg: makeNodeComponent("svg"),
    // Metadata about props expected for PlasmicHeading1GoogleUxChallenge
    internalVariantProps: PlasmicHeading1GoogleUxChallenge__VariantProps,
    internalArgProps: PlasmicHeading1GoogleUxChallenge__ArgProps
  }
);

export default PlasmicHeading1GoogleUxChallenge;
/* prettier-ignore-end */
