// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PlasmicHeading1BillieHome } from "./plasmic/new_ones/PlasmicHeading1BillieHome";

function Heading1BillieHome_(props, ref) {
  // Use PlasmicHeading1BillieHome to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicHeading1BillieHome are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all Heading1BillieHomeProps here, but feel free
  // to do whatever works for you.
  return <PlasmicHeading1BillieHome root={{ ref }} {...props} />;
}

const Heading1BillieHome = React.forwardRef(Heading1BillieHome_);

export default Heading1BillieHome;
