// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { NavContext } from "../components/plasmic/new_ones/PlasmicGlobalVariant__Nav";
import { NavBarButtonContext } from "../components/plasmic/new_ones/PlasmicGlobalVariant__NavBarButton";
import { PlasmicUxWritingBlogExercise1 } from "../components/plasmic/portfolio_bener/PlasmicUxWritingBlogExercise1";

function UxWritingBlogExercise1() {
  // Use PlasmicUxWritingBlogExercise1 to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicUxWritingBlogExercise1 are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, PlasmicUxWritingBlogExercise1 is wrapped by your project's global
  // variant context providers. These wrappers may be moved to
  // Next.js Custom App component
  // (https://nextjs.org/docs/advanced-features/custom-app).
  return (
    <NavBarButtonContext.Provider value={undefined}>
      <NavContext.Provider value={undefined}>
        <PlasmicUxWritingBlogExercise1 />
      </NavContext.Provider>
    </NavBarButtonContext.Provider>
  );
}

export default UxWritingBlogExercise1;
