// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 578p2KiWp3ZSUFPY7FrhK3
// Component: JjbA4Hm8LNdr-g
import * as React from "react";
import Link from "next/link";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_new_ones.module.css"; // plasmic-import: 578p2KiWp3ZSUFPY7FrhK3/projectcss
import sty from "./PlasmicNavMenuItemBase.module.css"; // plasmic-import: JjbA4Hm8LNdr-g/css
import NavIconBase2Icon from "./icons/PlasmicIcon__NavIconBase2"; // plasmic-import: MxSKl5EzDtcRZm/icon
import NavIconBase3Icon from "./icons/PlasmicIcon__NavIconBase3"; // plasmic-import: CwmdYknIlpmz7O/icon
import NavIconBaseIcon from "./icons/PlasmicIcon__NavIconBase"; // plasmic-import: 9s2ryVuI124WY_/icon

export const PlasmicNavMenuItemBase__VariantProps = new Array(
  "navMenuVariants"
);

export const PlasmicNavMenuItemBase__ArgProps = new Array();

function PlasmicNavMenuItemBase__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <p.Stack
      as={p.PlasmicLink}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.a,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root,
        {
          [sty.rootnavMenuVariants_gd]: hasVariant(
            variants,
            "navMenuVariants",
            "gd"
          ),

          [sty.rootnavMenuVariants_uix]: hasVariant(
            variants,
            "navMenuVariants",
            "uix"
          ),

          [sty.rootnavMenuVariants_uxWriting]: hasVariant(
            variants,
            "navMenuVariants",
            "uxWriting"
          )
        }
      )}
      component={Link}
      href={
        hasVariant(variants, "navMenuVariants", "gd")
          ? "/gd"
          : hasVariant(variants, "navMenuVariants", "uix")
          ? "/uiux-design"
          : "/ux-writing"
      }
      platform={"nextjs"}
      target={
        hasVariant(variants, "navMenuVariants", "gd")
          ? "_blank"
          : hasVariant(variants, "navMenuVariants", "uix")
          ? "_blank"
          : hasVariant(variants, "navMenuVariants", "uxWriting")
          ? "_blank"
          : undefined
      }
    >
      <p.PlasmicIcon
        data-plasmic-name={"svg"}
        data-plasmic-override={overrides.svg}
        PlasmicIconType={
          hasVariant(variants, "navMenuVariants", "gd")
            ? NavIconBase3Icon
            : hasVariant(variants, "navMenuVariants", "uix")
            ? NavIconBaseIcon
            : NavIconBase2Icon
        }
        className={classNames(projectcss.all, sty.svg, {
          [sty.svgnavMenuVariants_gd]: hasVariant(
            variants,
            "navMenuVariants",
            "gd"
          ),

          [sty.svgnavMenuVariants_uix]: hasVariant(
            variants,
            "navMenuVariants",
            "uix"
          ),

          [sty.svgnavMenuVariants_uxWriting]: hasVariant(
            variants,
            "navMenuVariants",
            "uxWriting"
          )
        })}
        role={"img"}
      />

      <p.Stack
        as={"div"}
        data-plasmic-name={"textAndSupportingText2"}
        data-plasmic-override={overrides.textAndSupportingText2}
        hasGap={true}
        className={classNames(projectcss.all, sty.textAndSupportingText2, {
          [sty.textAndSupportingText2navMenuVariants_gd]: hasVariant(
            variants,
            "navMenuVariants",
            "gd"
          ),

          [sty.textAndSupportingText2navMenuVariants_uxWriting]: hasVariant(
            variants,
            "navMenuVariants",
            "uxWriting"
          )
        })}
      >
        <p.Stack
          as={"div"}
          data-plasmic-name={"textAndBadge2"}
          data-plasmic-override={overrides.textAndBadge2}
          hasGap={true}
          className={classNames(projectcss.all, sty.textAndBadge2)}
        >
          <div
            data-plasmic-name={"text3"}
            data-plasmic-override={overrides.text3}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text3,
              {
                [sty.text3navMenuVariants_gd]: hasVariant(
                  variants,
                  "navMenuVariants",
                  "gd"
                ),

                [sty.text3navMenuVariants_uix]: hasVariant(
                  variants,
                  "navMenuVariants",
                  "uix"
                ),

                [sty.text3navMenuVariants_uxWriting]: hasVariant(
                  variants,
                  "navMenuVariants",
                  "uxWriting"
                )
              }
            )}
          >
            {hasVariant(variants, "navMenuVariants", "gd")
              ? "Graphic Design"
              : hasVariant(variants, "navMenuVariants", "uix")
              ? "UI/UX Design"
              : hasVariant(variants, "navMenuVariants", "uxWriting")
              ? "UX Writing"
              : "Heading"}
          </div>
        </p.Stack>

        <div
          data-plasmic-name={"theLatestIndustryNewsUpdatesAndInfo2"}
          data-plasmic-override={overrides.theLatestIndustryNewsUpdatesAndInfo2}
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.theLatestIndustryNewsUpdatesAndInfo2,
            {
              [sty.theLatestIndustryNewsUpdatesAndInfo2navMenuVariants_gd]:
                hasVariant(variants, "navMenuVariants", "gd"),
              [sty.theLatestIndustryNewsUpdatesAndInfo2navMenuVariants_uix]:
                hasVariant(variants, "navMenuVariants", "uix"),
              [sty.theLatestIndustryNewsUpdatesAndInfo2navMenuVariants_uxWriting]:
                hasVariant(variants, "navMenuVariants", "uxWriting")
            }
          )}
        >
          {hasVariant(variants, "navMenuVariants", "gd")
            ? "I’ve done a lot of graphic works in the past, check it out!"
            : hasVariant(variants, "navMenuVariants", "uix")
            ? "Selection of my work as a UI/UX Designer"
            : hasVariant(variants, "navMenuVariants", "uxWriting")
            ? "As an UI/UX, I want to know how to write, so that i can do better"
            : "Isi deskripsinya disini maximal 2 baris yep"}
        </div>
      </p.Stack>
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "svg",
    "textAndSupportingText2",
    "textAndBadge2",
    "text3",
    "theLatestIndustryNewsUpdatesAndInfo2"
  ],

  svg: ["svg"],
  textAndSupportingText2: [
    "textAndSupportingText2",
    "textAndBadge2",
    "text3",
    "theLatestIndustryNewsUpdatesAndInfo2"
  ],

  textAndBadge2: ["textAndBadge2", "text3"],
  text3: ["text3"],
  theLatestIndustryNewsUpdatesAndInfo2: ["theLatestIndustryNewsUpdatesAndInfo2"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicNavMenuItemBase__ArgProps,
      internalVariantPropNames: PlasmicNavMenuItemBase__VariantProps
    });

    return PlasmicNavMenuItemBase__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNavMenuItemBase";
  } else {
    func.displayName = `PlasmicNavMenuItemBase.${nodeName}`;
  }
  return func;
}

export const PlasmicNavMenuItemBase = Object.assign(
  // Top-level PlasmicNavMenuItemBase renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),
    textAndSupportingText2: makeNodeComponent("textAndSupportingText2"),
    textAndBadge2: makeNodeComponent("textAndBadge2"),
    text3: makeNodeComponent("text3"),
    theLatestIndustryNewsUpdatesAndInfo2: makeNodeComponent(
      "theLatestIndustryNewsUpdatesAndInfo2"
    ),

    // Metadata about props expected for PlasmicNavMenuItemBase
    internalVariantProps: PlasmicNavMenuItemBase__VariantProps,
    internalArgProps: PlasmicNavMenuItemBase__ArgProps
  }
);

export default PlasmicNavMenuItemBase;
/* prettier-ignore-end */
